//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/input/PlayerController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerController: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerController"",
    ""maps"": [
        {
            ""name"": ""Player1"",
            ""id"": ""18b2d364-6e65-40b8-932b-ecfa53e4b677"",
            ""actions"": [
                {
                    ""name"": ""MainShoot"",
                    ""type"": ""Button"",
                    ""id"": ""9f38fb21-947d-465c-8523-32919f290173"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""movment"",
                    ""type"": ""Value"",
                    ""id"": ""6b95cfbc-5f51-43e3-8efa-3fcf00f85f50"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""looking"",
                    ""type"": ""PassThrough"",
                    ""id"": ""81960c00-a0b6-49ac-b3da-2292714f30d5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiniGun"",
                    ""type"": ""Button"",
                    ""id"": ""4cb5c39b-380a-4148-9091-4b28762f4ead"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Artillery"",
                    ""type"": ""Button"",
                    ""id"": ""95e2545c-05bd-45e2-a2c0-beaeef6dc24d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rocket"",
                    ""type"": ""Button"",
                    ""id"": ""c6086c51-ff0f-4038-bbbe-e2f8bb10a3b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Conform"",
                    ""type"": ""Button"",
                    ""id"": ""7d1f2e37-375a-4e2f-9885-66a2a5606b63"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""secondShoot"",
                    ""type"": ""Button"",
                    ""id"": ""e4360b53-dbe1-4fc8-9799-193b8798ccd2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeapenMode"",
                    ""type"": ""Button"",
                    ""id"": ""f7c6814b-93de-4e3c-94df-5829e5c932a8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a63b33c2-6688-437e-90d9-1b926965b635"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MainShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f73e34d-2a4c-4187-b9f4-fc96f27d7132"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MainShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56871d8d-7b85-4ab4-adee-4490ed0f3c36"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MainShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""858ed4bc-da8c-4b9d-98c4-8829d2d5483b"",
                    ""path"": ""<XInputController>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fe3e485-59e1-4990-86e0-9f88fd26c4e9"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c09362e6-740a-4a18-862d-1afbcd860927"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movment"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1d021269-cb56-44fe-baad-eba795afc02a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""93a5014a-74e1-465c-ba92-2951fc0f3fdd"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5f4c56d3-652c-4751-88b5-abfc5f1a056e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4eb2f928-88ae-47d9-90a8-1389f8dc2288"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""bb84f9b8-b675-4503-a313-4f5362facf9d"",
                    ""path"": ""Dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movment"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""75748d7c-98b6-4566-a63a-4533c010f64b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""movment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""181c35d5-2696-41cf-8b25-2927c131a66c"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""movment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""be622e90-760a-4e2f-a426-d513e4c218c6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""movment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e70ef9b1-eba6-4fcf-8738-1551135c7216"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""movment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1390810b-380d-4dca-8edf-b9aef9f0e266"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""movment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""86fdc699-64d1-4fdc-a3e5-efde5643bb3c"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""movment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d85a5228-2040-4839-88cc-2356ba65fed8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""movment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c774ada9-c2de-44c0-ac71-53e76270d425"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""movment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""181e1797-4b56-422f-a166-8e2e86e84af1"",
                    ""path"": ""<XInputController>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""looking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2b7d9a5-ec73-4580-a107-2a4535c28d93"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""looking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""7b418cd7-84c2-4738-a2ce-43c209657e6b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""looking"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""fb8dac61-0f17-46f4-bcfb-12031f25aaa7"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""looking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5b7604c1-7437-4ce6-9a9e-760286b8b1a7"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""looking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b02cd7e4-df5b-4a61-a0a6-9b931f486bae"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""looking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""87c39078-f12e-425c-9eec-6e31b9105813"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""looking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b7d8f4f5-dee8-41b5-9d6e-912e44b10020"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MiniGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13cc3a03-3d94-4645-a6ae-802a75b9a073"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MiniGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""518d0b75-857d-460e-822e-fa60b0fd0edc"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MiniGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1849b93d-2b69-4b9d-9962-09ddf5ddec23"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Artillery"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e33bf49-e2dd-4db3-adc8-e8e8eefd63af"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Artillery"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""182dff5f-ae26-40d2-a26f-e38d61e05148"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Artillery"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b75ec5c1-aab4-44cc-b238-1895b950c663"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rocket"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f99a4269-64db-4d1b-8d11-681d06175c5b"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rocket"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc50ab0f-2bcd-43d3-b960-7cdf4a869818"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rocket"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac9c2c77-d07d-47f7-a6e3-593c995dc797"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Conform"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57c2c0c8-31ae-43a2-b4fd-ec2a4370dde7"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Conform"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b549163-8aa2-475e-8a8f-a1e14dd2a5fd"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Conform"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e055722-4333-41b1-b800-e2f1172843a7"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Conform"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""544ccf92-0ceb-43b7-9878-e6179ebc1e61"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""secondShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eacb6eef-b7e1-4bad-94e1-9f248242eb49"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""secondShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd0a0bbd-3744-47b6-b55c-dd64fa36f196"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""secondShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c9ef7d0-3830-44f8-89fe-b78af8391854"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39dbeeaf-2701-444a-9e43-78a87e19c61f"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5601a255-5701-4c44-9c09-aba2765e0092"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player1
        m_Player1 = asset.FindActionMap("Player1", throwIfNotFound: true);
        m_Player1_MainShoot = m_Player1.FindAction("MainShoot", throwIfNotFound: true);
        m_Player1_movment = m_Player1.FindAction("movment", throwIfNotFound: true);
        m_Player1_looking = m_Player1.FindAction("looking", throwIfNotFound: true);
        m_Player1_MiniGun = m_Player1.FindAction("MiniGun", throwIfNotFound: true);
        m_Player1_Artillery = m_Player1.FindAction("Artillery", throwIfNotFound: true);
        m_Player1_Rocket = m_Player1.FindAction("Rocket", throwIfNotFound: true);
        m_Player1_Conform = m_Player1.FindAction("Conform", throwIfNotFound: true);
        m_Player1_secondShoot = m_Player1.FindAction("secondShoot", throwIfNotFound: true);
        m_Player1_WeapenMode = m_Player1.FindAction("WeapenMode", throwIfNotFound: true);
    }

    ~@PlayerController()
    {
        UnityEngine.Debug.Assert(!m_Player1.enabled, "This will cause a leak and performance issues, PlayerController.Player1.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player1
    private readonly InputActionMap m_Player1;
    private List<IPlayer1Actions> m_Player1ActionsCallbackInterfaces = new List<IPlayer1Actions>();
    private readonly InputAction m_Player1_MainShoot;
    private readonly InputAction m_Player1_movment;
    private readonly InputAction m_Player1_looking;
    private readonly InputAction m_Player1_MiniGun;
    private readonly InputAction m_Player1_Artillery;
    private readonly InputAction m_Player1_Rocket;
    private readonly InputAction m_Player1_Conform;
    private readonly InputAction m_Player1_secondShoot;
    private readonly InputAction m_Player1_WeapenMode;
    public struct Player1Actions
    {
        private @PlayerController m_Wrapper;
        public Player1Actions(@PlayerController wrapper) { m_Wrapper = wrapper; }
        public InputAction @MainShoot => m_Wrapper.m_Player1_MainShoot;
        public InputAction @movment => m_Wrapper.m_Player1_movment;
        public InputAction @looking => m_Wrapper.m_Player1_looking;
        public InputAction @MiniGun => m_Wrapper.m_Player1_MiniGun;
        public InputAction @Artillery => m_Wrapper.m_Player1_Artillery;
        public InputAction @Rocket => m_Wrapper.m_Player1_Rocket;
        public InputAction @Conform => m_Wrapper.m_Player1_Conform;
        public InputAction @secondShoot => m_Wrapper.m_Player1_secondShoot;
        public InputAction @WeapenMode => m_Wrapper.m_Player1_WeapenMode;
        public InputActionMap Get() { return m_Wrapper.m_Player1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player1Actions set) { return set.Get(); }
        public void AddCallbacks(IPlayer1Actions instance)
        {
            if (instance == null || m_Wrapper.m_Player1ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Player1ActionsCallbackInterfaces.Add(instance);
            @MainShoot.started += instance.OnMainShoot;
            @MainShoot.performed += instance.OnMainShoot;
            @MainShoot.canceled += instance.OnMainShoot;
            @movment.started += instance.OnMovment;
            @movment.performed += instance.OnMovment;
            @movment.canceled += instance.OnMovment;
            @looking.started += instance.OnLooking;
            @looking.performed += instance.OnLooking;
            @looking.canceled += instance.OnLooking;
            @MiniGun.started += instance.OnMiniGun;
            @MiniGun.performed += instance.OnMiniGun;
            @MiniGun.canceled += instance.OnMiniGun;
            @Artillery.started += instance.OnArtillery;
            @Artillery.performed += instance.OnArtillery;
            @Artillery.canceled += instance.OnArtillery;
            @Rocket.started += instance.OnRocket;
            @Rocket.performed += instance.OnRocket;
            @Rocket.canceled += instance.OnRocket;
            @Conform.started += instance.OnConform;
            @Conform.performed += instance.OnConform;
            @Conform.canceled += instance.OnConform;
            @secondShoot.started += instance.OnSecondShoot;
            @secondShoot.performed += instance.OnSecondShoot;
            @secondShoot.canceled += instance.OnSecondShoot;
            @WeapenMode.started += instance.OnWeapenMode;
            @WeapenMode.performed += instance.OnWeapenMode;
            @WeapenMode.canceled += instance.OnWeapenMode;
        }

        private void UnregisterCallbacks(IPlayer1Actions instance)
        {
            @MainShoot.started -= instance.OnMainShoot;
            @MainShoot.performed -= instance.OnMainShoot;
            @MainShoot.canceled -= instance.OnMainShoot;
            @movment.started -= instance.OnMovment;
            @movment.performed -= instance.OnMovment;
            @movment.canceled -= instance.OnMovment;
            @looking.started -= instance.OnLooking;
            @looking.performed -= instance.OnLooking;
            @looking.canceled -= instance.OnLooking;
            @MiniGun.started -= instance.OnMiniGun;
            @MiniGun.performed -= instance.OnMiniGun;
            @MiniGun.canceled -= instance.OnMiniGun;
            @Artillery.started -= instance.OnArtillery;
            @Artillery.performed -= instance.OnArtillery;
            @Artillery.canceled -= instance.OnArtillery;
            @Rocket.started -= instance.OnRocket;
            @Rocket.performed -= instance.OnRocket;
            @Rocket.canceled -= instance.OnRocket;
            @Conform.started -= instance.OnConform;
            @Conform.performed -= instance.OnConform;
            @Conform.canceled -= instance.OnConform;
            @secondShoot.started -= instance.OnSecondShoot;
            @secondShoot.performed -= instance.OnSecondShoot;
            @secondShoot.canceled -= instance.OnSecondShoot;
            @WeapenMode.started -= instance.OnWeapenMode;
            @WeapenMode.performed -= instance.OnWeapenMode;
            @WeapenMode.canceled -= instance.OnWeapenMode;
        }

        public void RemoveCallbacks(IPlayer1Actions instance)
        {
            if (m_Wrapper.m_Player1ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayer1Actions instance)
        {
            foreach (var item in m_Wrapper.m_Player1ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Player1ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Player1Actions @Player1 => new Player1Actions(this);
    public interface IPlayer1Actions
    {
        void OnMainShoot(InputAction.CallbackContext context);
        void OnMovment(InputAction.CallbackContext context);
        void OnLooking(InputAction.CallbackContext context);
        void OnMiniGun(InputAction.CallbackContext context);
        void OnArtillery(InputAction.CallbackContext context);
        void OnRocket(InputAction.CallbackContext context);
        void OnConform(InputAction.CallbackContext context);
        void OnSecondShoot(InputAction.CallbackContext context);
        void OnWeapenMode(InputAction.CallbackContext context);
    }
}
